import Head from 'next/head'
import Navbar from '../../components/Navbar'
import CollectionsBody from '../../components/CollectionsBody'
import { useWeb3 } from '@3rdweb/hooks'
import { useRouter } from 'next/router'
import { ThirdwebSDK } from '@3rdweb/sdk'



// let collectionId: any

function Collections({props}: any) {
  //router.query

  console.log({props})

  return (
    <div className={``}>
      <Head>
        <title>Enefti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <CollectionsBody collection={props} />
    </div>
  )
}


export async function getServerSideProps() {

  // const router = useRouter()
  // const collectionId = router

  const sdk = new ThirdwebSDK("https://eth-goerli.g.alchemy.com/v2/C56CKHL7TSuSazmgkLFHX0fiOmtv3CrW");
  const nftModule = sdk.getNFTModule('0x2cb5aD4e8060719781F9BaA94493B4BcD2AdF1Ba');

  const _nfts = await nftModule.getAll();
  console.log(_nfts)

  return {
    props: {
      props: _nfts
    }
  }
}

export default Collections


//0x2cb5aD4e8060719781F9BaA94493B4BcD2AdF1Ba