import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
//import Mainbody from '../components/Mainbody'
import Landing from '../components/Landing'
//import ConnectWallet from '../components/ConnectWallet'
// import { useWeb3 } from '@3rdweb/hooks'
// import { useMetamask, useAddress } from '@thirdweb-dev/react'
// import toast, {Toaster} from 'react-hot-toast'
import { useEffect } from 'react'

const Home: NextPage = () => {

  //const {address, connectWallet} = useWeb3()
  // const connectWithMetamask = useMetamask()
  // const address = useAddress()

  // if (!address) {
  //   return (
  //     <>
  //       <Navbar />
  //       <div className={`w-full h-[100vh] ${styles.landing}`}>
  //         <div className={`w-full h-[100vh] flex flex-col justify-start items-center pt-[5rem] ${styles.backdrop}`}>
  //           <img className={`w-[15rem] h-[15rem] rounded-full my-2`} alt='' src='/icons/logo.jpg' />
  //           <p className={`text-white text-2xl my-2 tracking-wide`}>Not Logged In?</p>
  //           <button className={`w-[20rem] h-[2.5rem] text-base text-white bg-[#1877f2] mr-8 rounded-lg font-bold tracking-wide my-2`} onClick = {connectWithMetamask}>Connect With Metamask</button>
  //         </div>
  //       </div>
  //     </>
  //   )
  // } else

  // const welcomeUser = (user: string, toastHandler = toast)=>{
  //   toastHandler.success(
  //     `Welcome to Enefti, ${user}!`,
  //     {
  //       style: {
  //         background: '#04111d',
  //         color: 'fff'
  //       }
  //     }
  //   )
  // }

  // useEffect(()=>{
  //   if(address){
  //     welcomeUser(`${address.slice(0,4)}...${address.slice(address.length - 4)}`)
  //   }
  // }, [address])

    return (
      <div className={styles.container}>
        <Head>
          <title>Enefti</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <Toaster position={'top-center'} reverseOrder= {false}/> */}
        <Navbar />
        <Landing />
      </div>
    )
}

export default Home
