import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Landing from '../components/Landing'
import { useEffect } from 'react'

const Home: NextPage = () => {

    return (
      <div className={styles.container}>
        <Head>
          <title>Enefti</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Landing />
      </div>
    )
}

export default Home
