import Head from 'next/head'
import Navbar from '../components/Navbar'
import CollectionsBody from '../components/CollectionsBody'



function Marketplace() {
  
  return (
    <div className={`font-roboto`}>
      <Head>
        <title>Enefti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <CollectionsBody/>
    </div>
  )
}


export default Marketplace

